# Generated by Django 4.0.6 on 2022-07-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='activity_flag',
            field=models.CharField(blank=True, choices=[('Active', 'Активована'), ('NotActive', 'Не активована'), ('Stitched', 'Прострочена')], default='NotActive', max_length=10, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='card',
            name='sum_card',
            field=models.FloatField(blank=True, null=True, verbose_name='Сума'),
        ),
    ]
