# Generated by Django 4.0.6 on 2022-07-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cards', '0003_alter_card_expiration_date_alter_card_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Номер картки'),
        ),
    ]
